# Alternative Railway Configuration (Shell Script)
# Use this version if the main railway.toml doesn't work

[build]
builder = "NIXPACKS"

[deploy]
# Use shell script approach
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway will automatically set PORT
DEBUG = "False"
CORS_ORIGIN = "*"
