[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python3 -m src.app"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production]
variables = { DEBUG = "False", CORS_ORIGIN = "*", PYTHONUNBUFFERED = "1" }
