# Alternative Railway Configuration (Simpler)
# Use this version if the main railway.toml doesn't work

[build]
builder = "NIXPACKS"

[deploy]
# Simple approach - just run the app.py directly
startCommand = "python3 src/app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway will automatically set PORT
DEBUG = "False"
CORS_ORIGIN = "*"
