[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "chmod +x start_railway.sh && ./start_railway.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environments.production]
variables = { DEBUG = "False", CORS_ORIGIN = "*", PYTHONUNBUFFERED = "1" }
