# Railway Deployment Configuration
# This file tells Railway how to deploy your FastAPI app

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn src.app:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# Railway will automatically set PORT
# Add your environment variables in Railway dashboard
DEBUG = "False"
CORS_ORIGIN = "*"
