# DigitalOcean App Platform Configuration
# This file defines how your app will be deployed on DigitalOcean

name: financial-prediction-api
region: nyc
domains:
- domain: your-domain.com  # Replace with your domain
  type: PRIMARY

services:
- name: fastapi
  source_dir: /
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs  # $5/month
  routes:
  - path: /
  environment_slug: python
  envs:
  - key: DEBUG
    value: "False"
  - key: CORS_ORIGIN
    value: "https://your-domain.com"
  - key: REDIS_HOST
    value: "${redis.HOSTNAME}"
  - key: REDIS_PORT
    value: "${redis.PORT}"
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"

- name: celery-worker
  source_dir: /
  dockerfile_path: Dockerfile
  instance_count: 2  # 2 workers
  instance_size_slug: basic-xxs
  run_command: celery -A src.celery_app worker --loglevel=info --concurrency=2 --queues=bulk_predictions
  envs:
  - key: DEBUG
    value: "False"
  - key: REDIS_HOST
    value: "${redis.HOSTNAME}"
  - key: REDIS_PORT
    value: "${redis.PORT}"
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"

databases:
- name: db
  engine: PG
  size: basic  # $15/month
  num_nodes: 1
  version: "14"

- name: redis
  engine: REDIS
  size: basic  # $15/month
  num_nodes: 1
  version: "7"

static_sites: []

jobs: []

workers: []
